#pragma once

#define RESOURCE_DLL_LIBMYSQL	100
#define RESOURCE_DLL_LIBCRYPTO	101
#define RESOURCE_DLL_LIBSSL		102

#define RESOURCE_DATA   		200
#define RESOURCE_GDPR_CHECK   	201

#define RESOURCE_SQL_MYSQL		300
#define RESOURCE_SQL_SQLITE3	301
